### ISSUE TITLE
Support nested context and params that are not set to be null

### ISSUE THREAD

**Issue by krishnamiriyala** [AFriemann/mdc#1]
I was exactly trying to add something similar on the same day as you :) and saw your package.

Would you be able to support nested context and context when some of the params are null?

```
+def test_mdc_formatter():
+    formatter = MDCFormatter('[%(foo)s/%(bar)s/%(blah)s] - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
+    hndlr.setFormatter(formatter)
+    @with_mdc(bar='def')
+    def bar(ctx, x):
+        logging.debug(x)
+        assert ctx.bar == 'def', ctx.bar
+        assert ctx.foo == 'abc', ctx.foo
+
+    @with_mdc(foo='abc')
+    def foo(ctx, x):
+        logging.debug(x)
+        bar(1)
+        assert ctx.foo == 'abc', ctx.foo
+    foo(1)
```

**Comment by AFriemann** [comment]
Hey @krishnambm ! 

thank you for the issue :)

Unfortunately I'm not sure this is what you're looking for. The MDCFormatter outputs json right now and I don't have the use case for specific formatting. (I'm only using this in Containers with an EFK for log tracing) 

However, I get what you are trying to achieve and I see the value. If you have a good Idea how to implement this send me a pull request and we'll discuss it further.

**Comment by AFriemann** [comment]
Sorry, I'm a bit trigger happy :D

**Comment by krishnambm** [comment]
Sure I am new to github, will try to add pull request asap, happy to hear to listen that you are open to changes :)

**Comment by AFriemann** [comment]
no worries. If you have any trouble with it just send me a mail!

**Comment by krishnambm** [comment]
Created a pull request let me know if it looks non-disruptive to your changes
